### PR TITLE
Create 2019-04-08--libp2p-sync.md

### PR DESCRIPTION
**Pull request by bigs**
Call notes and recording link for 4/9/2019 call. Please review the notes (or watch the video) and approve.

### CODE REVIEW

**Comment by anacrolix** [comment]
I'm timing out getting the video from the link https://ipfs.io/ipfs/QmVC1AAFLPhnBh2xEJC8Jhrjs7BLW1fa183CGQvsvygQXS.

**Comment by mgoelzer** [comment]
@bigs Let's you and I both aim to post the cryptpad on the Friday morning before the meeting.  (This is Saturday on the other side of the dateline, but it at least gives everyone one full business day to fill in.) /cc @marten-seemann 

@bigs:  Regarding @anacrolix 's comment, I've generally been posting the videos on YouTube only.  I do like the idea of dogfooding our own tech, so maybe we should do both an IPFS video link and YouTube link.  Note that the Youtube channel has an audience of subscribers who won't know about ipfs video links, so they both have value in different ways.  What do you think?

**Comment by mgoelzer** [comment]
ping @anacrolix , @jhiesey

**Comment by anacrolix** [comment]
Sorry I was just trying to view the video and the IPFS link was on the cryptpad. I didn't know it was also on YouTube.

**Comment by mgoelzer** [comment]
@anacrolix I'm not sure it's also on youtube.  @bigs does the alternate week calls; idk if he puts them on youtube, though we should probably standardize.

@bigs, some folks were saying the ipfs recording didn't work for this video (w/ or w/o gateways)

**Pull request merged**
