### PR TITLE
Update with new sync call protocol

### PR DESCRIPTION
**Pull request by mgoelzer**
Just updated the call information, how to find call recordings, etc.

### CODE REVIEW

**Comment by jacobheun** [comment]
Some things I think we should add to make this a bit easier:
1. Add a template for the notes to this repo. This allows anyone to easily create a Cryptpad for the next meeting. 
2. Add a section to this readme or the notes template (preferable) about expectation of roles. For example, having the notetaker/moderator be responsible for creating the PR of the notes after the call. 
    a. Have the moderator create the items for the next meeting as a new comment in https://github.com/libp2p/team-mgmt/issues/16. If we do this after each weeks meeting it should help us make sure we don't run into an issue where non attending members don't have a cryptpad to post in. Although if we have a template, anyone should be able to create the issue :)
3. After the video has been uploaded I think it's also helpful to add the url to the original issue, https://github.com/libp2p/team-mgmt/issues/16#issuecomment-476381951, for example. We do this in the js ipfs core meetings https://github.com/ipfs/team-mgmt/issues/650#issuecomment-478593345 and I think it makes it easy for people to use that as a central reference point for finding everything.

**Comment by mgoelzer** [comment]
@jacobheun Thanks for the feedback.  These all seem reasonable.  @bigs and I are still sorting out who is responsible for what, so give us a little tine.  

I'm going to copy/paste what you wrote into an issue in this repo so we can not lose it once this PR gets merged.

**Comment by mgoelzer** [comment]
Ping @bigs 

I'm going to self merge if you aren't able to review this week.  These are simple changes, and I think it's important for people looking at the front page of the repo to see accurate information about when the call is happening.

**Comment by bigs** [comment]
sorry, lumped notifications for this in with the monday agenda! good by me.

**Comment by bigs** [comment]
@jacobheun i have such a template in cryptpad and can add it here!

**Comment by bigs** [comment]
Added the template

**Pull request merged**
